version: "3.8"


services:
  web:
    build: .
    container_name: front
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://temir.ae
      - API_URL=http://167.172.67.40

  nginx:
    build: ./nginx
    image: nginx:1.21-alpine
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"