version: "3.8"


services:
  web:
    build: .
    container_name: front
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    image: nginx:1.21-alpine
    restart: always
    depends_on:
      - web
    volumes:
      - web-root:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
    command:
      - certonly --webroot --webroot-path=/var/www/html --email temircard@gmail.com --agree-tos --no-eff-email --staging -d temir.ae
volumes:
  certbot-etc:
  certbot-var:
  web-root:
  etc-letsencrypt: