version: "3.8"


services:
  web:
    build: .
    container_name: front
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    image: nginx:1.21-alpine
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"